config/routes.rb
Sqlsite::Application.routes.draw do
  resources :dashboards

  resources :users ,:user_sessions

  match 'login' => 'user_sessions#new', :as => :login
  match 'logout' => 'user_sessions#destroy', :as => :logout

  match 'dashboards/query/:db/:table/:offset',:to=>'dashboards#query'

end

app/models/dashboard.rb
class Dashboard < ActiveRecord::Base
  belongs_to :user
end

app/controllers/dashboards_controller.rb
class DashboardsController < ApplicationController
  before_filter  :admin_or_user_required
  # GET /dashboards
  # GET /dashboards.json
  def index
    @dashboard =  current_user.dashboard unless current_user.dashboard.nil?

    respond_to do |format|
      format.html # index.html.erb
      format.json { render :json=> @dashboard }
    end
  end

  # GET /dashboards/1
  # GET /dashboards/1.json
  def show
    @dashboard = current_user.dashboard
    @db_tables=UserDatabase::ReadDb.new(@dashboard.db_name)
    @tables=@db_tables.get_tables

    @tab_hash=Hash.new
    @tables.each do |table|
       col=  @db_tables.get_columns(table.first)
       @arr=Hash.new
       col.each_with_index do |c,index|
         @ah=Hash.new
         @ah[c[0]]=c[1]
         @arr[index]=@ah
       end
    @tab_hash[table.first]=@arr
    end

     respond_to do |format|
      format.html # show.html.erb
      format.json { render :json=> @dashboard }
    end
  end

  # GET /dashboards/new
  # GET /dashboards/new.json
  def new
    @dashboard = current_user.build_dashboard if current_user.dashboard.nil?

    respond_to do |format|
      format.html # new.html.erb
      format.json { render :json=> @dashboard }
    end
  end

  # GET /dashboards/1/edit
  def edit
    @dashboard = current_user.dashboard
  end

  # POST /dashboards
  # POST /dashboards.json
  def create
    if current_user.dashboard.nil?
      @dashboard = Dashboard.new(params[:dashboard])
      @dashboard.user=current_user
      respond_to do |format|
        if @dashboard.save
          @db=UserDatabase::CreateDb.new(@dashboard.db_name)
          @db.create

          format.html { redirect_to @dashboard, :notice=> 'Database created.' }
          format.json { render :json=> @dashboard, :status=> :created, :location=> @dashboard }
        else
          format.html { render :action=> "new" }
          format.json { render :json=> @dashboard.errors, :status=> :unprocessable_entity }
        end
      end
    else
      respond_to do |format|
          format.html { render :action=> "new" }
          format.json { render :json=> @dashboard.errors, :status=> :unprocessable_entity }
      end
    end
  end

  # PUT /dashboards/1
  # PUT /dashboards/1.json
  def update
    @dashboard = current_user.dashboard

    respond_to do |format|
      if @dashboard.update_attributes(params[:dashboard])
        format.html { redirect_to @dashboard, :notice=> 'Dashboard was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render :action=> "edit" }
        format.json { render :json=> @dashboard.errors, :status=> :unprocessable_entity }
      end
    end
  end

  # DELETE /dashboards/1
  # DELETE /dashboards/1.json
  def destroy
    @dashboard = Dashboard.find(params[:id])
    @dashboard.destroy

    respond_to do |format|
      format.html { redirect_to dashboards_url }
      format.json { head :ok }
    end
  end


  def query
    db= params[:db]
    @table= params[:table]
    @offset=params[:offset]
    @dashboard = current_user.dashboard
    if @dashboard and @dashboard.db_name==db
      @db_tables=UserDatabase::ReadDb.new(@dashboard.db_name)
      @row_count=@db_tables.get_data_count(@table)
       @row_count.each do |count|
      @rc=Integer( count.first)
      end
      @out= @db_tables.show_data(@table,50,@offset)

      if @rc >=50
        @next=Integer(@offset)+50
        @previous=Integer(@offset)-50
      else
        @next=0
        @previous=0
      end

      render :partial=> 'table'
    else
      # render an error page
       render :file => "../../public/404.html"
    end
end
end

app/helpers/dashboards_helper.rb
module DashboardsHelper
end

app/views/dashboards/_form.html.erb
<%= form_for(@dashboard) do |f| %>
  <% if @dashboard.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@dashboard.errors.count, "error") %> prohibited this dashboard from being saved:</h2>

      <ul>
      <% @dashboard.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :db_name %><br />
    <%= f.text_field :db_name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/dashboards/_table.html.erb
<% content_for :custom_scripts do %>

<% end %>
<% @out.each do |rows| %>
    <tr class='row-contents'>
      <% rows.each do |row| %>
          <td><%= row %><td>
      <% end %>
    </tr>

<% end %>
<% if @rc >=50 and @next<=@rc %>
        <tr class='next-button'>
  <% if @next !=50 %>
    <td><%= link_to '<< Previous',"/dashboards/query/#{@dashboard.db_name}/#{@table}/#{@previous}" ,:remote=>true,:class=>"table_name",:id=>"prev_#{@table}" %></td>
    <td>|</td>
  <% end %>
    <td><%= link_to 'Next >>',"/dashboards/query/#{@dashboard.db_name}/#{@table}/#{@next}" ,:remote=>true,:class=>"table_name",:id=>"next_#{@table}" %></td>
  </tr>
<% elsif @rc>=50 and @next>@rc %>
  <tr class='next-button'><td><%= link_to '<< Previous',"/dashboards/query/#{@dashboard.db_name}/#{@table}/#{@previous}" ,:remote=>true,:class=>"table_name",:id=>"prev_#{@table}" %></td></tr>
<% end %>

<script type="text/javascript">

  $("a#next_<%=@table %>").bind("ajax:complete", function(et, e){
       $('tr').remove('.row-contents');
      $('tr').remove('.next-button');
       $("#<%=@table %>_table").append(e.responseText); // insert content

    });

   $("a#prev_<%=@table %>").bind("ajax:complete", function(et, e){
       $('tr').remove('.row-contents');
      $('tr').remove('.next-button');
       $("#<%=@table %>_table").append(e.responseText); // insert content

    });



</script>

app/views/dashboards/edit.html.erb
<h1>Editing dashboard</h1>

<%= render 'form' %>

<%= link_to 'Show', @dashboard %> |
<%= link_to 'Back', dashboards_path %>

app/views/dashboards/index.html.erb
<h1>Listing dashboards</h1>

<table>
  <tr>
    <th>Db name</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

  <% if @dashboard %>
  <tr>
    <td><%= @dashboard.db_name %></td>
    <td><%= link_to 'Show', @dashboard %></td>
    <td><%= link_to 'Edit', edit_dashboard_path(@dashboard) %></td>
    <td><%= link_to 'Destroy', @dashboard, :confirm=> 'Are you sure?', :method=> :delete %></td>
  </tr>
  <% end %>
</table>

<br />
<% if ! @dashboard %>
    <%= link_to 'New Dashboard', new_dashboard_path %>
<% end %>

app/views/dashboards/new.html.erb
<h1>New dashboard</h1>

<%= render 'form' %>

<%= link_to 'Back', dashboards_path %>

app/views/dashboards/show.html.erb
<% content_for :custom_scripts do %>

<%= javascript_tag do %>
 $(document).ready(function () {
  <% @tab_hash.each do |taber,cols| %>
  $("img#refresh_<%=taber %>").hide();
   $("a#<%=taber %>_a").hide();
   $("span.<%=taber %>_span").hide();
   $("#<%=taber %>_table").hide();


   $('#vert_class_<%= taber %>').click(function() {
      alert("Hello");
   });

   $("a#<%=taber %>").bind("ajax:before", function(et, e){
     if( $("span.<%=taber %>_span").is(":visible") ) {
         $('table.datTables').hide();
         $("#<%=taber %>_table").show();
         $('a.refresh_button').hide();
         $("a#<%=taber %>_a").show();
         return false;
        }
      else
         $("img#refresh_<%=taber %>").show();

   });

   $("a#<%=taber %>").bind("ajax:complete", function(et, e){

        $("#<%=taber %>_table").append(e.responseText); // insert content
        $("img#refresh_<%=taber %>").hide();
        $('a.refresh_button').hide();
        $("a#<%=taber %>_a").show();
        $("span.<%=taber %>_span").show();
        $('table.datTables').hide();

        $("#<%=taber %>_table").show();

  });


   $("a#<%=taber %>_a").bind("ajax:complete", function(et, e){
         $('tr').remove('.row-contents');
         $('tr').remove('.next-button');
        $("#<%=taber %>_table").append(e.responseText); // insert content
        $("img#refresh_<%=taber %>").hide();
        $('a.refresh_button').hide();
        $("a#<%=taber %>_a").show();
        $("span.<%=taber %>_span").show();
        $('table.datTables').hide();

        $("#<%=taber %>_table").show();

  });



 <% end %>

  });
<% end %>


<% end %>

<p id="notice"><%= notice %></p>

<p>
  <b>Db name:</b>
  <%= @dashboard.db_name %>
</p>

<%= link_to 'Edit', edit_dashboard_path(@dashboard) %> |
<%= link_to 'Back', dashboards_path %>

<h3>Tables</h3>
<% @tab_hash.each do |table,columns| %>
  <ul  id="freedom" class="idTabs"><%= link_to table,"/dashboards/query/#{@dashboard.db_name}/#{table}/0" ,:remote=>true,:class=>"table_name",:id=>table %>

     <img src="../assets/loading.gif" alt="alternative text" width='24px' height='24px' id="refresh_<%= table%>" />
    <% columns.each do |key,value| %>
        <%   value.each do |k,v| %>
            <li><%= k %>&nbsp;(&nbsp;<%= v %>&nbsp;)</li>
        <% end %>

    <% end %>
  </ul>

<% end %>




<div class='tabContainer'>

    <% @tab_hash.each do |table,columns| %>
    <%= link_to "Refresh", "/dashboards/query/#{@dashboard.db_name}/#{table}/0", :id=>"#{table}_a",:remote=>true, :class=>'refresh_button' %><span class='<%=table %>_span'></span>
    <div id="vert_<%=table %>">
    <table id='<%=table %>_table' style="position:absolute;" class="datTables">
        <tr>
         <% columns.each do |column,value| %>
              <%   value.each do |k,v| %>
                    <th><%=k %></th>
              <% end %>

         <% end %>
        </tr>

    </table>
    </div>


    <% end %>



</div>